/**
 * B&B Shuffle - Printable Session Sheet
 *
 * Builds a compact, print-only one-pager for the current game: the four
 * scenario cards WITH their DETECTION lists (card art is unreadable at print
 * size, so the Procedure names that detect each card are printed as text), the
 * procedure hand (with Enhanced/+3 markers and tick boxes), the whole inject
 * queue with the current inject flagged, the seated consultant, live
 * turn/strike state and a notes block that rules itself down to the footer.
 *
 * Why a separate DOM instead of printing the board:
 *   - only the CURRENT inject is ever in the board DOM, so a CSS-only print
 *     of the board could never list the rest of the inject queue;
 *   - the board relies on `backface-visibility` + 3D transforms to hide card
 *     faces, and those are unreliable in print;
 *   - text beats cropped card art on paper.
 *
 * The sheet's FRAME is static markup in `player.html` - the deck cover (which
 * stands in for the B&B logo, its fallback), the session logo, the rules and the
 * notes box. Only `#ps-head-text`, `#ps-stats` and `#ps-body` are rewritten here,
 * and only when their HTML actually changed: an <img> created during the print
 * snapshot has not decoded yet and paints blank, which is what used to happen to
 * the masthead logo.
 *
 * Styles live in `Engine-V2/css/player.css` (tail, `@media print`). They only
 * hide the app when <body> carries `print-has-sheet`, so printing with no
 * scenario loaded falls back to the normal browser behaviour.
 *
 * Self-mounting like CardViewer: a page only needs `#print-sheet-btn` and
 * `#print-sheet` in its markup plus this script tag after `player.js`.
 */
(function (global) {
    'use strict';

    const BTN_ID = 'print-sheet-btn';
    const OUT_ID = 'print-sheet';
    const HEAD_ID = 'ps-head-text';
    const BODY_ID = 'ps-body';
    const STATS_ID = 'ps-stats';
    const COVER_ID = 'ps-cover';
    const MARK_LOGO_ID = 'ps-mark-logo';
    const LINES_ID = 'ps-note-lines';
    const MARK_ID = 'ps-custom-mark';
    const MARK_IMG_ID = 'ps-custom-logo';
    const BODY_CLASS = 'print-has-sheet';
    // Generated by docs/build_card_details.py, and the only detection-bearing
    // artefact reachable at runtime (.dockerignore drops docs/card-detection.json
    // and docs/detection/, which are the generator's inputs).
    const CATALOG_URL = '../docs/card-details.json';
    // The notes box shares whatever height the paper leaves above the footer
    // between this many lines (see .ps-note-line in css/player.css), so this is
    // a pitch hint rather than a fit calculation.
    const NOTE_LINES = 12;
    // Canonical in Utils (utils.js loads before this file) - as are the labels.
    const SCENARIO_TYPES = Utils.SCENARIO_TYPES;
    const TYPE_LABELS = Utils.CARD_TYPE_LABELS;

    let btn = null;
    let out = null;
    let bound = false;
    let prevTitle = null;
    // Last HTML written to each half of the sheet.
    let headHtml = null;
    let bodyHtml = null;
    let statsHtmlCache = null;

    // The DETECTION index, built once per page load. Best effort: a failure
    // just means the sheet prints without the cross-references.
    let catalogPromise = null;
    let catalog = null;   // { byDeck: Map<deckKey, {byName, byImage}>, byImage: Map }

    // ---------------------------------------------------------------- helpers

    // Escaping delegates to the canonical Utils.escapeHtml. The inline copy only
    // runs if utils.js failed to load - and it must still escape, never pass the
    // value through raw (which is what this fallback used to do).
    function esc(value) {
        if (global.Utils && typeof Utils.escapeHtml === 'function') return Utils.escapeHtml(value);
        return String(value == null ? '' : value)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');
    }

    function asset(src) {
        if (!src) return '';
        return (global.Utils && typeof Utils.assetPath === 'function') ? Utils.assetPath(src) : src;
    }

    function typeLabel(type) {
        return TYPE_LABELS[type] || type || '';
    }

    function controller() {
        return (typeof PlayerController !== 'undefined') ? PlayerController : null;
    }

    function game() {
        return (typeof GameState !== 'undefined' && GameState.game) ? GameState.game : null;
    }

    function byId(id) {
        return document.getElementById(id);
    }

    /**
     * Normalise an image path to the form the catalog uses.
     *
     * `carddb.json` spells card art from `shared/decks/<deck>/`
     * (`../../shared/decks/core/initial-1.webp`) while `docs/card-details.json`
     * stores the same file as `decks/core/initial-1.webp` - the form the
     * Catalogue's own `imgUrl()` produces. Both collapse to
     * `decks/core/initial-1.webp`, which is why the index is keyed by IMAGE
     * rather than by deck + name: mega-deck and the sponsor decks reprint other
     * decks' art, and one name can be a different physical card per deck.
     * @param {string} src - Stored image path
     * @returns {string} Lowercased `decks/...` key ('' when there is no path)
     */
    function imageKey(src) {
        const value = String(src || '');
        const idx = value.indexOf('shared/decks/');
        const rel = idx >= 0 ? value.slice(idx + 'shared/'.length) : value.replace(/^(\.\.\/)+/, '');
        return rel.toLowerCase();
    }

    /**
     * Index the catalog: deck key -> {byName, byImage}, plus a global byImage
     * fallback for cards whose art lives in another deck's folder.
     * @param {Object} data - Parsed docs/card-details.json
     * @returns {{byDeck: Map, byImage: Map}}
     */
    function indexCatalog(data) {
        const byDeck = new Map();
        const byImage = new Map();

        ((data && data.decks) || []).forEach(function (deck) {
            const deckByName = new Map();
            const deckByImage = new Map();

            Object.keys(deck.cards || {}).forEach(function (type) {
                (deck.cards[type] || []).forEach(function (card) {
                    // The key is ABSENT (never []) when a card's DETECTION list has
                    // not been read yet; only initial|pivot|c2|persist carry it.
                    if (!card || !Array.isArray(card.detection) || !card.detection.length) return;
                    const key = imageKey(card.image);
                    if (key) {
                        if (!deckByImage.has(key)) deckByImage.set(key, card.detection);
                        if (!byImage.has(key)) byImage.set(key, card.detection);
                    }
                    if (card.name) {
                        const name = String(card.name).toLowerCase();
                        if (!deckByName.has(name)) deckByName.set(name, card.detection);
                    }
                });
            });

            if (deck.deck) byDeck.set(deck.deck, { byName: deckByName, byImage: deckByImage });
        });

        return { byDeck: byDeck, byImage: byImage };
    }

    /** Fetch + index the catalog once per page load. */
    function loadCatalog() {
        if (!catalogPromise) {
            catalogPromise = fetch(CATALOG_URL, { cache: 'force-cache' })
                .then(function (response) { return response.ok ? response.json() : null; })
                .then(function (data) {
                    catalog = indexCatalog(data);
                    return catalog;
                })
                .catch(function () {
                    catalog = { byDeck: new Map(), byImage: new Map() };
                    return catalog;
                });
        }
        return catalogPromise;
    }

    /**
     * The DETECTION list for a scenario card: the card's own list when the deck
     * carries one, otherwise the catalog entry for the same art (falling back to
     * the same name within the active deck).
     * @param {Object} card - Scenario card data
     * @returns {string[]} Procedure names (empty when not recorded)
     */
    function detectionsFor(card) {
        const own = (card && Array.isArray(card.detection)) ? card.detection : null;
        if (own && own.length) {
            return own.map(function (entry) {
                return typeof entry === 'string' ? entry : (entry && entry.name) || '';
            }).filter(Boolean);
        }
        if (!catalog || !card) return [];

        const controllerObj = controller();
        const deckKey = ((controllerObj && controllerObj.scenario && controllerObj.scenario.deck) || {}).key;
        const deck = catalog.byDeck.get(deckKey);
        const key = imageKey(card.image);
        if (deck) {
            if (key && deck.byImage.has(key)) return deck.byImage.get(key);
            const name = String(card.name || '').toLowerCase();
            if (deck.byName.has(name)) return deck.byName.get(name);
        }
        return (key && catalog.byImage.get(key)) || [];
    }

    // ------------------------------------------------------------- fragments

    function headHtmlFor(scenario) {
        const meta = scenario.metadata || {};
        const deck = scenario.deck || {};
        // The scenario's own export stamp reads as "this is when this table's game
        // was written down"; fall back to when it was created.
        const stamp = scenario.exportDate || meta.exportDate || meta.createdAt;
        let when = '';
        if (stamp) {
            const date = new Date(stamp);
            if (!isNaN(date.getTime())) {
                when = date.toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' });
            }
        }
        const metaLine = [
            deck.name,
            meta.author ? 'by ' + meta.author : '',
            when
        ].filter(Boolean).join(' · ');

        return '<p class="ps-eyebrow">Session Sheet</p>'
            + '<h2 class="ps-title">' + esc(meta.name || deck.name || 'Scenario') + '</h2>'
            + (metaLine ? '<p class="ps-meta">' + esc(metaLine) + '</p>' : '');
    }

    /**
     * The four live-state figures. The CONTAINER is `#ps-stats` in the static
     * frame (it owns the `.ps-stats` class and the rule under the strip), so this
     * returns the stats only — wrapping them again nested a second `.ps-stats`,
     * and the inner flex row shrink-wrapped to its content, painting a short
     * second line under the real one.
     */
    function statsHtml(controllerObj) {
        const state = game() || {};
        const config = (controllerObj.scenario && controllerObj.scenario.gameConfig) || {};
        const procedures = (controllerObj.scenario.procedures || []).length;

        function stat(value, label) {
            return '<div class="ps-stat">'
                + '<span class="ps-stat-value">' + esc(String(value)) + '</span>'
                + '<span class="ps-stat-label">' + esc(label) + '</span>'
                + '</div>';
        }

        return stat(state.turnsRemaining == null ? '' : state.turnsRemaining, 'turns left')
            + stat((state.strikeCount || 0) + ' / ' + (state.maxStrikes || config.maxStrikes || 3), 'strikes used')
            + stat(controllerObj.successTarget || 11, 'roll target')
            + stat(procedures, procedures === 1 ? 'procedure' : 'procedures');
    }

    /**
     * The four scenario slots, each with its DETECTION list underneath.
     * A card that has no list print "Not yet recorded" rather than nothing: the
     * catalog key is absent for roughly half of the printed scenario cards, and
     * an empty gap reads as an omission.
     */
    function scenarioCardsHtml(scenario) {
        const cards = SCENARIO_TYPES.map(function (type) {
            const card = (scenario.scenario || {})[type];
            if (!card) return '';
            const detections = detectionsFor(card);
            const list = detections.length
                ? '<ul>' + detections.map(function (name) {
                    return '<li>' + esc(name) + '</li>';
                }).join('') + '</ul>'
                : '<p class="ps-detection-none">Not yet recorded</p>';

            return '<div class="ps-card">'
                + '<div class="ps-card-head">'
                + '<img class="ps-thumb" src="' + esc(asset(card.image)) + '" alt="" decoding="sync"'
                + ' onerror="Utils.onImgError(event)">'
                + '<div class="ps-card-title">'
                + '<span class="ps-type">' + esc(typeLabel(type)) + '</span>'
                + '<span class="ps-name">' + esc(card.name || typeLabel(type)) + '</span>'
                + '</div>'
                + '</div>'
                + '<div class="ps-detection">'
                + '<span class="ps-detection-label">Detection</span>'
                + list
                + '</div>'
                + '</div>';
        }).join('');

        return '<h3 class="ps-h">Scenario Cards</h3>'
            + '<div class="ps-cards">' + cards + '</div>';
    }

    function columnHtml(title, count, rows, empty) {
        return '<section>'
            + '<h3 class="ps-h">' + esc(title) + ' <span class="ps-count">' + count + '</span></h3>'
            + '<ol class="ps-list">'
            + (rows || '<li class="ps-row is-empty">' + esc(empty) + '</li>')
            + '</ol>'
            + '</section>';
    }

    function procedureRows(procedures) {
        return procedures.map(function (card, index) {
            return '<li class="ps-row' + (card.enhanced ? ' is-enhanced' : '') + '">'
                + '<span class="ps-index">' + (index + 1) + '.</span>'
                + '<span class="ps-check" aria-hidden="true"></span>'
                + '<span class="ps-row-name">' + esc(card.name || 'Procedure') + '</span>'
                + (card.enhanced ? '<span class="ps-badge">✦ +3</span>' : '')
                + '</li>';
        }).join('');
    }

    function injectRows(controllerObj) {
        const queue = controllerObj.injectQueue || [];
        return queue.map(function (card, index) {
            const current = index === controllerObj.activeInjectIndex;
            return '<li class="ps-row' + (current ? ' is-current' : '') + '">'
                + '<span class="ps-index">' + (index + 1) + '.</span>'
                + '<span class="ps-check" aria-hidden="true"></span>'
                + '<span class="ps-row-name">' + esc((card && card.name) || 'Inject') + '</span>'
                + (current ? '<span class="ps-badge">Current</span>' : '')
                + '</li>';
        }).join('');
    }

    function bodyHtmlFor(controllerObj) {
        const scenario = controllerObj.scenario;
        const procedures = scenario.procedures || [];
        const injects = controllerObj.injectQueue || [];
        const consultant = controllerObj.consultant;

        return scenarioCardsHtml(scenario)
            + '<div class="ps-cols">'
            + columnHtml('Procedures', procedures.length, procedureRows(procedures), 'No procedure cards')
            + columnHtml('Inject Queue', injects.length, injectRows(controllerObj), 'No injects queued')
            + '</div>'
            + '<h3 class="ps-h">Consultant</h3>'
            + '<p class="ps-consultant">' + esc((consultant && consultant.name) || 'none called yet') + '</p>';
    }

    // ------------------------------------------------------------------ API

    /**
     * Fill the sheet from the current game state and mark it printable.
     * @returns {boolean} Whether there is anything to print
     */
    function build() {
        const controllerObj = controller();
        if (!out || !controllerObj || !controllerObj.scenario) return false;

        // Write only what changed. Re-writing a half replaces the <img> elements
        // inside it, and a freshly created image is not guaranteed to have
        // decoded by the time the browser takes its print snapshot.
        const nextStats = statsHtml(controllerObj);
        const nextHead = headHtmlFor(controllerObj.scenario);
        const nextBody = bodyHtmlFor(controllerObj);
        const stats = byId(STATS_ID);
        const head = byId(HEAD_ID);
        const body = byId(BODY_ID);
        if (stats && nextStats !== statsHtmlCache) {
            stats.innerHTML = nextStats;
            statsHtmlCache = nextStats;
        }
        if (head && nextHead !== headHtml) {
            head.innerHTML = nextHead;
            headHtml = nextHead;
        }
        if (body && nextBody !== bodyHtml) {
            body.innerHTML = nextBody;
            bodyHtml = nextBody;
        }

        out.classList.add('is-ready');
        document.body.classList.add(BODY_CLASS);
        return true;
    }

    /**
     * Give the sheet's notes area its writing lines. Each line has a preferred
     * height and the box clips them (see .ps-note-line in css/player.css), so the
     * lines share out whatever the paper leaves above the footer.
     */
    function buildNoteLines() {
        const box = byId(LINES_ID);
        if (!box || box.childElementCount) return;
        box.innerHTML = Array.from({ length: NOTE_LINES }, function () {
            return '<div class="ps-note-line"></div>';
        }).join('');
    }

    /**
     * Put this session's uploaded logo (Theme -> logo) in the sheet's masthead.
     *
     * The <img> itself is static in player.html, so it is part of the document
     * well before any print. A src assigned here is decoded before returning,
     * because a fresh image that has not decoded yet paints blank in the print
     * snapshot (which is what used to happen to the masthead logo).
     * @returns {Promise<void>}
     */
    function syncLogo() {
        const wrap = byId(MARK_ID);
        const img = byId(MARK_IMG_ID);
        if (!wrap || !img) return Promise.resolve();

        // Absent `bb-theme-logo` means the bundled default, not "no logo": the
        // sheet always shows the B&B mark, and only `logoShow = 0` removes it.
        const uploaded = Utils.getFromStorage('bb-theme-logo', null);
        const shown = Utils.getFromStorage('bb-theme-logoShow', null) !== '0';
        if (!uploaded || !shown) {
            wrap.classList.remove('has-logo');
            return Promise.resolve();
        }
        if (img.getAttribute('src') !== uploaded) {
            img.setAttribute('src', uploaded);
            wrap.classList.add('has-logo');
            if (typeof img.decode === 'function') {
                return img.decode().catch(function () { /* decode() is best effort */ });
            }
        }
        wrap.classList.add('has-logo');
        return Promise.resolve();
    }

    /**
     * Show the deck's box art at the head of the sheet - it REPLACES the
     * standalone B&B logo, which the box art already carries.
     *
     * Like the logo the <img> is static markup in `player.html`, so it is part of
     * the document long before any print; the src assigned here is decoded before
     * returning, because an image that has not decoded yet paints blank on paper.
     * Decks with no box art (and a board with no deck at all) fall back to the
     * bundled print logo rather than leaving the corner empty.
     * @returns {Promise<void>}
     */
    function syncCover() {
        const img = byId(COVER_ID);
        const logo = byId(MARK_LOGO_ID);
        if (!img) return Promise.resolve();

        const controllerObj = controller();
        const deckKey = (controllerObj && controllerObj.scenario && controllerObj.scenario.deck)
            ? controllerObj.scenario.deck.key : '';
        const deck = (deckKey && typeof CONFIG !== 'undefined' && CONFIG.decks) ? CONFIG.decks[deckKey] : null;

        if (!deck || !deck.cover) {
            img.removeAttribute('src');
            Utils.hideElement(img);
            if (logo) Utils.showElement(logo);
            return Promise.resolve();
        }
        Utils.showElement(img);
        if (logo) Utils.hideElement(logo);
        if (img.getAttribute('src') === deck.cover) return Promise.resolve();
        img.setAttribute('src', deck.cover);
        img.alt = (deck.name || deckKey) + ' box art';
        if (typeof img.decode === 'function') {
            return img.decode().catch(function () { /* decode() is best effort */ });
        }
        return Promise.resolve();
    }

    /**
     * Keep the button (and the sheet) in step with the board.
     *
     * Only rebuilds when asked to (`force`): the board is populated
     * asynchronously, so a build triggered from `init()` can run while
     * `PlayerController.scenario` is already set but `injectQueue` is not yet.
     * The real funnels are `setupGame()` (force) and `beforeprint`/the button.
     */
    function refresh(force) {
        if (!btn) return;
        const controllerObj = controller();
        const ready = !!(controllerObj && controllerObj.scenario);
        btn.disabled = !ready;
        btn.title = ready
            ? 'Print a one-page session sheet (scenario cards, their detection lists, the hand and the inject queue)'
            : 'Load a scenario first — the sheet prints the cards in play';
        if (!ready) return;

        if (force) {
            syncCover();
            build();
        }
        // Warm the DETECTION index as soon as a game is on the board, so the
        // first print is not also the first fetch. The rebuild that follows is a
        // no-op unless the lists actually changed something.
        loadCatalog().then(function () {
            syncCover();
            build();
        });
    }

    function print() {
        const controllerObj = controller();
        if (!controllerObj || !controllerObj.scenario) {
            if (global.Utils && typeof Utils.showToast === 'function') {
                Utils.showToast('Load a scenario before printing a session sheet', 'warning');
            }
            return Promise.resolve();
        }
        // Normally already resolved (refresh() prefetches it), so window.print()
        // still runs inside the click; the first print of a session waits on the
        // fetch.
        return loadCatalog().then(syncLogo).then(syncCover).then(function () {
            if (!build()) return;
            // Most browsers use the document title for the print header and the
            // suggested PDF filename.
            prevTitle = document.title;
            const name = (controllerObj.scenario.metadata || {}).name;
            document.title = name ? 'Session Sheet — ' + name : 'Session Sheet';
            // Give the freshly built thumbnails a frame to paint before the
            // browser snapshots the page for the print preview.
            requestAnimationFrame(function () {
                setTimeout(function () { global.print(); }, 0);
            });
        });
    }

    function restoreTitle() {
        if (prevTitle !== null) {
            document.title = prevTitle;
            prevTitle = null;
        }
    }

    function init() {
        btn = byId(BTN_ID);
        out = byId(OUT_ID);
        if (!btn || !out) return;   // page doesn't want a session sheet

        if (!bound) {
            bound = true;
            btn.addEventListener('click', print);
            // Rebuild for Ctrl+P / the browser menu too, not just the button.
            global.addEventListener('beforeprint', function () { syncLogo(); syncCover(); build(); });
            global.addEventListener('afterprint', restoreTitle);
            // `setupGame()` is the single funnel for starting a game (init,
            // Quick Start and Load all reach it), so wrap it to rebuild the
            // sheet once every field — including injectQueue — is populated.
            const board = controller();
            if (board && typeof board.setupGame === 'function') {
                const originalSetup = board.setupGame;
                board.setupGame = function () {
                    const result = originalSetup.apply(this, arguments);
                    refresh(true);
                    return result;
                };
            }
            // Keep the masthead logo in step with the Theme modal: by the time it
            // closes, an upload's async storage write has landed.
            ['theme-modal-done', 'theme-modal-close'].forEach(function (id) {
                const el = byId(id);
                if (el) el.addEventListener('click', syncLogo);
            });
        }

        buildNoteLines();
        syncLogo();
        syncCover();
        refresh();
    }

    global.PrintSheet = {
        isEnabled: function () { return !!btn && !btn.disabled; },
        build: build,
        refresh: refresh,
        print: print
    };

    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
    else init();
})(window);
